# Generated by Django 2.2.3 on 2020-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20200707_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.IntegerField(verbose_name='Precio en $'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono o Celular'),
        ),
    ]
